# Site settings
title: SZiccardi
name: Shelby Ziccardi
email: shelbyziccardi@gmail.com
url: https://github.com/sziccardi
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
keywords: "research, computer science, phd, human motion analysis, motion capture"
skills: "Research, Human Movement Analysis, Simulation"
meta_author: Ziccardi Shelby

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: A1BAA4
  primary-rgb: "161,186,164"
  secondary: 472D30
  secondary-dark: 01161E 

# Footer settings
footer:
  copyright: Shelby Ziccardi
  location: University of Minnesota
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/sziccardi
  - title: linkedin
    url: https://www.linkedin.com/in/shelby-ziccardi/
  - title: Applied Motion Lab
    url: https://motion.cs.umn.edu/
  - title: Neural Rehabilitation Lab
    url: https://neural.umn.edu/

# Postal address (add as many lines as necessary)
# address:
#   - line: 3481 Melrose Place
#   - line: Beverly Hills, CA 90210

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
